### ISSUE TITLE
como administrador quiero iniciar sesion para administrar todo el contenido del sitio web

### ISSUE THREAD

**Issue by ljavierrodriguez** [ljavierrodriguez/ljavierrodriguez#1]
- [ ] debe facilitar usuario y contraseña
- [ ] los campos usuario y contraseña no pueden estar vacios
- [ ] la contraseña debe cumplir los siquientes parametros: 
- minimo 8 caracteres
- debe contener una mayuscula, una minuscula y un numero
